spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=xio
    username: sa
    password: admin
  main:
    banner-mode: off
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: ${PORT:8090}