spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:10.19.90.45}:1433;databaseName=xio
    username: ${DB_USER:sa}
    password: ${DB_PASS:skq123456}
  main:
    banner-mode: off
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: ${PORT:8090}
