spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=xio
    username: sa
    password: admin
  main:
    banner-mode: off
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: mybatis/mapper/*.xml
  configuration:
    # 该属性将开启驼峰映射，非常重要:
    map-underscore-to-camel-case: true
server:
  port: ${PORT:8090}

---

spring:
  config:
    activate:
      on-profile: xio
  datasource:
    url: jdbc:sqlserver://${DB_HOST:10.19.90.45}:1433;databaseName=xio
    username: ${DB_USER:sa}
    password: ${DB_PASS:skq123456}
